name: Publish docs via GitHub
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install \
            "wheel" \
            "lxml" \
            "mkdocs-material" \
            "cairosvg>=2.5" \
            "mkdocs-git-committers-plugin-2>=1.1.1" \
            "mkdocs-git-revision-date-localized-plugin>=1.0" \
            "mkdocs-minify-plugin>=0.3" \
            "mkdocs-rss-plugin>=1.2" \
            "mkdocs-redirects>=1.0" \
            "pillow<10"

      - name: Deploy documentation
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force
          mkdocs --version

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages

      - name: Copy search.html to gh-pages
        run: |
          cp search.html ./search.html
          git add search.html
          git commit -m "Add search.html to gh-pages"

      - name: Push changes to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin gh-pages
